#adicionando a porta e nome da aplicação
server:
 port: 8100
#caminho do eureka
eureka:
 client:
    service-url:
      defalteZone: http://localhost:8761/eureka 
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book_service
    username: postgres
    password: Bel2107
  #resolvendo problema de beans vazio
  jackson:
    default-property-inclusion: non-null
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: none    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
        jdbc:
          lob:
            non-contextual-creation: true
    show-sql: true 