server:
  port: 8080
spring:
  application:
    name: greeting-service
  config:
    import:
    - optional:configserver:http://localhost:8888/
    #para mais opçoes vão embaixo
  cloud:
    config:
      profile: prod
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
#retirando o greeting server 
greeting-service:
  greeting: "Olá"
  default-value: "Mundo"
