#definindo a porta e nome da aplicação
server:
  port: 8000
spring:
  application:
    name: cambio-service
  #propriedade de config para bd MySQL
  #datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver 
    #url: jdbc:mysql://localhost:3306/cambio_service?userTimezone=true&serveTimezone=UTC
    #username: root
    #password: admin123
  #jpa:
    #hibernate:
      #ddl-auto: update    
    #show-sql: true    #mostra o sql gerado, apenas para teste em produção ele consome recurso
    #properties:
      #hibernate:
       #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  #flyway:
   #url: jdbc:mysql://localhost:3306/
   #schemas: cambio_service
   #user: root
   #password: admin123
#configuração para postgreSQL
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cambio_service?userTimezone=true&serveTimezone=UTC
    username: postgres
    password: Bel2107
  jpa:
    hibernate:
      ddl-auto: update    
    show-sql: true    
    properties:
      hibernate:
       dialect: org.hibernate.dialect.PostgreSQL81Dialect
  flyway:
   url: jdbc:postgresql://localhost:5432/
   schemas: cambio_service
   user: postgres
   password: Bel2107
#trocar o scrip para o do postegre no migration
