#definindo a porta e nome da aplicação
server:
  port: 8000
spring:
  application:
    name: cambio-service
 #configuração do eureka
      
  #propriedade de config para bd MySQL
  #datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver 
    #url: jdbc:mysql://localhost:3306/cambio_service?userTimezone=true&serveTimezone=UTC
    #username: root
    #password: admin123
  #jpa:
    #hibernate:
      #ddl-auto: update    
    #show-sql: true    #mostra o sql gerado, apenas para teste em produção ele consome recurso
    #properties:
      #hibernate:
       #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  #flyway:
   #url: jdbc:mysql://localhost:3306/
   #schemas: cambio_service
   #user: root
   #password: admin123
#configuração para postgreSQL
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cambio_service
    username: postgres
    password: Bel2107
  jpa:
    hibernate:
      ddl-auto: none    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
        jdbc:
          lob:
            non-contextual-creation: true
    show-sql: false 
  
eureka:
  client:
    service-url:
      defalteZone: http://localhost:8761/eureka #caminho do eureka 
#para reslver problema de erro do caminho da url do loud balance     
#springdoc:
 #api-docs:
    #path: cambio-service/v3/api-docs
  #padrão em que está no navegador v3/api-docs
    
  
#trocar o scrip para o do postegre no migration
